server:
  port: 8191
# JMS Configuration
spring:
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 5
      max-concurrency: 10
    pub-sub-domain: true
    template:
      default-destination: topic1
      delivery-mode: non-persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000
  activemq:
    broker-url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=1
    user: admin
    password: admin
    packages:
        trust-all: false
        trusted: com.rs.app
  
# Logging Configuration
logging:
  pattern:
    console: "%msg%n"
  level:
      root: info
      org.springframework.: info
      com.rs.app.: info