server:
  port: 8192
# JMS Configuration
spring:
  jms:  
    cache:
      session-cache-size: 10
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 5
      max-concurrency: 10
    pub-sub-domain: false
    template:
      default-destination: 
      delivery-mode: non-persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000
  activemq:
    broker-url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=2
    user: admin
    password: admin
    packages:
        trust-all: false
        trusted: com.rs.app
